version: "3"
services:
 mvc4app:
  container_name: "mohamed_mvc4_co"
  build:
   context: ./src
   dockerfile: MVC4/Dockerfile
  ports:
   - "3000:80"
   - "3001:433"
  environment:
   - ASPNETCORE_URLS=http://+:80;https://+:433
   - ASPNETCORE_HTTPS_PORT=3001
   - ASPNETCORE_ENVIRONMENT=Development
   - ASPNETCORE_Kestrel__Certificates__Default__Password=AAaa@123456
   - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/MVC4.pfx
  volumes:
   - ~/.aspnet/https:/https:ro