version: '3.8'
services:
   ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        container_name: sqlserver_express
        hostname: sqlserver
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "AAaa@123456"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
   mvc-app:
        build:
         context: ./src
         dockerfile: ./MVC/Dockerfile-WithoutWaitTool
        image: mohamed/mvc_application
        container_name: mvc_application
        depends_on: 
            - ms-sql-server
        restart: on-failure:15
        environment:           
            DBServer: "ms-sql-server"
            ASPNETCORE_ENVIRONMENT: "Development"
        ports:
            - "1002:80"
      
