version: '3.4'
services:
   ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        container_name: sqlserver_express
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "AAaa@123456"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
   mvc-app:
        build: .
        image: mohamed/mvc_application
        container_name: mvc_application
        depends_on: 
            - ms-sql-server
        environment:           
            DBServer: "ms-sql-server"
            ASPNETCORE_ENVIRONMENT: "Development"
            WAIT_HOSTS: ms-sql-server:1433
            WAIT_HOSTS_TIMEOUT: 300
            WAIT_BEFORE_HOSTS: 20
            WAIT_HOST_CONNECT_TIMEOUT: 10
            WAIT_SLEEP_INTERVAL: 10
        ports:
            - "2020:80"
      